### ISSUE TITLE
Replace the old GIF in the README

### ISSUE THREAD

**Issue by 0l1v3rr** [0l1v3rr/github-readme-tech-stack#139]
### Describe the feature
In our [README](https://github.com/0l1v3rr/github-readme-tech-stack#readme), there is a [GIF](https://github.com/0l1v3rr/github-readme-tech-stack/blob/master/docs/github-readme-tech-stack.gif) of the [project's website](https://github-readme-tech-stack.vercel.app). We would like to replace this GIF with a better-quality one. Also, the website has been updated with minor changes and we would like to show it off as well.

### What should happen while recording the GIF
1. Change the title to `Demo Website`
2. Choose a nice dark theme from the drop-down menu
3. Add one or two badges (it's the little `+` below the `Line 1` )
4. Click on the `Generate` button and wait until the preview changes. Make sure you wait 0.5-1 second after the card has generated itself so we can see the result.

Of course, you can include more actions to show off the site's features.

### Checklist
- [ ] In the README, the old GIF is replaced with the new one and is exactly in the same position.
- [ ] The GIF is uploaded to the `docs/` folder and referenced from there in the README.
- [ ] The GIF is cropped so that only the main content of the page is visible.
- [ ] The GIF is high quality and everything is clearly readable.

### Additional context
- We are open to any ideas. Feel free to make suggestions in the comments section or by opening a new topic.
- If you want to start working on this task, please write a comment so I can assign you this issue.

**Comment by RKirlew** [comment]
Thank you! Made the update and created PR
