### ISSUE TITLE
The generated image is cutting and not showing all the badges

### ISSUE THREAD

**Issue by hrqmonteiro** [0l1v3rr/github-readme-tech-stack#247]
![Screenshot_20230721_160033](https://github.com/0l1v3rr/github-readme-tech-stack/assets/17055027/4d81f515-3da6-4cc7-b8f4-3589ebd6b85d)
![Screenshot_20230721_160041](https://github.com/0l1v3rr/github-readme-tech-stack/assets/17055027/b88ac723-d415-4771-8f40-49c43678edf6)
![Screenshot_20230721_160133](https://github.com/0l1v3rr/github-readme-tech-stack/assets/17055027/e70b7cbc-fd83-4a5c-9d72-607901e9cedd)

Looks like the 'line' config is not persisting

**Comment by 0l1v3rr** [comment]
Hi,

the `lines` config sets the number of lines you can add badges to. It does not automatically wrap the badges to the next line. If the
