### ISSUE TITLE
Extend the README with a short GIF

### ISSUE THREAD

**Issue by 0l1v3rr** [0l1v3rr/github-readme-tech-stack#31]
**Describe the feature**  
In the project's [README](https://github.com/0l1v3rr/github-readme-tech-stack#readme), we have a [screenshot](https://github.com/0l1v3rr/github-readme-tech-stack/blob/master/docs/demo-site-2.png) of the [project's website](https://github-readme-tech-stack.vercel.app). It would be great to replace it with a short **GIF**, so everyone could see a better preview of the project.

**What should happen while playing the GIF:**
1. Change the title to `Demo Website`
2. Select a good-looking dark theme from the dropdown
3. Add one or two badges (it's the little `+` under the `Line 1` )
4. Click on the `Generate` button and wait until the preview changes

**Here's a little checklist:**
- [ ] In the README, the screenshot is replaced with the GIF and is exactly in the same position
- [ ] The GIF is uploaded in the `docs/` folder and referred from there in the README 
- [ ] The GIF is cropped, so only the site's main content is visible

**Additional context**
We are open to every idea. Feel free to give us any suggestions in the comment section, or by opening a new issue.

**Comment by ShashwatAgrawal20** [comment]
hey @0l1v3rr would like to work on this

**Comment by 0l1v3rr** [comment]
Hey @ShashwatAgrawal20, awesome! I assigned you the issue.

**Comment by ShashwatAgrawal20** [comment]
@0l1v3rr will it be ok I do it tomorrow

**Comment by 0l1v3rr** [comment]
Yeah, sounds great!
